# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-11 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.PositiveSmallIntegerField()),
                ('people', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=1024)),
                ('title_en', models.CharField(max_length=1024, null=True)),
                ('title_de', models.CharField(max_length=1024, null=True)),
                ('description', models.TextField()),
                ('description_en', models.TextField(null=True)),
                ('description_de', models.TextField(null=True)),
                ('required_resources', models.TextField()),
                ('required_resources_en', models.TextField(null=True)),
                ('required_resources_de', models.TextField(null=True)),
            ],
        ),
    ]
