# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-11 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20180211_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='phase',
            name='name_de',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='phase',
            name='name_en',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='stage',
            name='name_de',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='stage',
            name='name_en',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
