# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-11 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20180211_1453'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='description_de',
            new_name='description_ca',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='required_resources_de',
            new_name='description_es',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='title_de',
            new_name='title_ca',
        ),
        migrations.RenameField(
            model_name='phase',
            old_name='name_de',
            new_name='name_ca',
        ),
        migrations.RenameField(
            model_name='stage',
            old_name='name_de',
            new_name='name_ca',
        ),
        migrations.AddField(
            model_name='game',
            name='required_resources_ca',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='required_resources_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='title_es',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='phase',
            name='name_es',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='stage',
            name='name_es',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
