# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-11 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_auto_20180211_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=1024)),
                ('description_en', models.CharField(max_length=1024, null=True)),
                ('description_es', models.CharField(max_length=1024, null=True)),
                ('description_ca', models.CharField(max_length=1024, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='game',
            name='phase',
            field=models.ManyToManyField(to='games.Material'),
        ),
    ]
