# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-11 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_auto_20180211_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='material',
            field=models.ManyToManyField(to='games.Material'),
        ),
        migrations.AlterField(
            model_name='game',
            name='phase',
            field=models.ManyToManyField(to='games.Phase'),
        ),
    ]
