# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-11 15:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_auto_20180211_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='required_resources',
        ),
        migrations.RemoveField(
            model_name='game',
            name='required_resources_ca',
        ),
        migrations.RemoveField(
            model_name='game',
            name='required_resources_en',
        ),
        migrations.RemoveField(
            model_name='game',
            name='required_resources_es',
        ),
    ]
