# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-11 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_auto_20180211_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='short_description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='short_description_ca',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='short_description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='short_description_es',
            field=models.TextField(null=True),
        ),
    ]
